export enum DB_Model {
  ACADEMIC_YEAR = 'academic_year',
  ADMIN = 'admin',
  CLASS = 'class',
  NOTIFY = 'notify',
  MAILER = 'mailer',
  OTP = 'otp',
  PARENTS_OR_GUARDIAN = 'parents_guardian',
  IMAGE = 'image',
  SCHOOL = 'school',
  STUDENT = 'student',
  STUDENT_ATTENDANCE = 'student_attendance',
  TEACHER = 'teacher',
  USER = 'user',
}
