export enum DB_Model {
  ACADEMIC_YEAR = 'academic_year',
  ADMIN = 'admin',
  CLASS = 'class',
  CLASS_SCHEDULE = 'class_schedule',
  CLASS_SUBJECT = 'class_subject',
  PROFILE_IMAGE = 'profile_image',
  PARENTS_OR_GUARDIAN = 'parents_guardian',
  SCHOOL = 'school_profile',
  STUDENT = 'student',
  STUDENT_ATTENDANCE = 'student_attendance',
  SUBJECT_GROUP = 'subject_group',
  TEACHER = 'teacher',
  USER = 'user',
}
