export const DEFAULT_CLASSES = [
  { id: 1, className: 'Nursery', order: 0 },
  { id: 2, className: 'LKG', order: 1 },
  { id: 3, className: 'UKG', order: 2 },
  { id: 4, className: 'Class 1', order: 3 },
  { id: 5, className: 'Class 2', order: 4 },
  { id: 6, className: 'Class 3', order: 5 },
  { id: 7, className: 'Class 4', order: 6 },
  { id: 8, className: 'Class 5', order: 7 },
  { id: 9, className: 'Class 6', order: 8 },
  { id: 10, className: 'Class 7', order: 9 },
  { id: 11, className: 'Class 8', order: 10 },
  { id: 12, className: 'Class 9', order: 11 },
  { id: 13, className: 'Class 10', order: 12 },
  { id: 14, className: 'Class 11', order: 13, streamsRequired: true },
  { id: 15, className: 'Class 12', order: 14, streamsRequired: true },
];
